services:
  - type: web
    name: sanskrit-ocr-crnn
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OCR_DEVICE
        value: cpu
